language: python
python:
  - "2.7"
cache: pip

# command to run tests
script:
 - ./manage.py runtests
 - pep8 --statistics --show-source

# Don't send email notifications
notifications:
  email: false
